import { z } from "zod";
import { PermitType, PermitTypeDefinition } from "./types";

export const HotWorkSchema = z.object({
  hotWorkType: z.enum(["welding", "grinding", "cutting", "soldering"]),
  fireWatchAssigned: z.string().min(2, "Fire watch person name is required"),
  fireExtinguisherType: z.enum(["CO2", "DCP", "Foam", "Water"]),
  combustiblesClearedRadius: z.number().min(5, "Combustibles must be cleared within at least 5m (10m recommended)"),
  gasTestLelPercent: z.number().min(0).max(10, "LEL must be < 5% to safely issue hot work"),
  gasTestO2Percent: z.number().min(19.5, "O2 level must be >= 19.5%").max(23.5, "O2 level must be <= 23.5%"),
  gasTestTestedAt: z.string().min(1, "Gas test timestamp is required"),
  gasTesterName: z.string().min(2, "Name of certified gas tester is required"),
});

export const ConfinedSpaceSchema = z.object({
  spaceId: z.string().min(2, "Space ID (e.g. Tank T-402, Vessel V-101) is required"),
  entryPoint: z.string().min(2, "Entry point designation is required"),
  atmosphericTestO2: z.number().min(19.5, "O2 must be >= 19.5%").max(23.5, "O2 must be <= 23.5%"),
  atmosphericTestLel: z.number().min(0).max(5, "LEL must be 0% (or < 5%)"),
  atmosphericTestH2sPpm: z.number().min(0).max(10, "H2S must be < 10 ppm"),
  atmosphericTestCoPpm: z.number().min(0).max(25, "CO must be < 25 ppm"),
  atmosphericTestTime: z.string().min(1, "Atmospheric test time is required"),
  atmosphericTesterName: z.string().min(2, "Tester name is required"),
  standbyAttendantName: z.string().min(2, "Dedicated Standby Attendant name is required"),
  rescuePlan: z.string().min(10, "Rescue plan details (tripod, harness, winch, emergency contact) required"),
  ventilationMethod: z.string().min(2, "Ventilation method (e.g. Forced Air Blower) required"),
  entryExitLogSummary: z.string().optional(),
});

export const WorkingAtHeightSchema = z.object({
  heightInMetres: z.number().min(1.8, "Working at height procedures apply to work at 1.8m or higher"),
  accessMethod: z.enum(["scaffold", "ladder", "MEWP", "rope"]),
  fallArrestEquipment: z.string().min(3, "Specify fall arrest equipment (e.g. Full body double-lanyard harness)"),
  anchorPointChecked: z.boolean().refine((val) => val === true, "Anchor point must be inspected and certified"),
  barricadingBelow: z.boolean().refine((val) => val === true, "Ground drop-zone barricading must be established"),
});

export const ElectricalLotoSchema = z.object({
  equipmentTag: z.string().min(2, "Equipment tag/label is required"),
  voltageLevel: z.string().min(2, "Voltage level is required (e.g. 415V AC, 3.3kV, 11kV)"),
  isolationPointsList: z.string().min(5, "List of physical isolation points (valves/breakers) is required"),
  lockNumbers: z.string().min(1, "Padlock ID numbers are required"),
  tagNumbers: z.string().min(1, "Danger Tag ID numbers are required"),
  earthingApplied: z.boolean().default(false),
  testedDeadByWhom: z.string().min(2, "Certified person who performed zero-voltage dead test is required"),
});

export const ExcavationSchema = z.object({
  excavationDepthMeters: z.number().min(0.5, "Depth in metres"),
  soilType: z.enum(["Type A (Clay/Hard)", "Type B (Silt/Sandy Loam)", "Type C (Gravel/Loose Sand)"]),
  undergroundUtilityClearance: z.boolean().refine((val) => val === true, "Cable & pipe locator scan must be verified"),
  shoringOrBenchMethod: z.string().min(3, "Shoring / Trench box / 45° sloping method required"),
  safeLadderDistanceMeters: z.number().max(7.5, "Egress ladder must be within 7.5m of workers"),
  spoilPileDistanceMeters: z.number().min(1.0, "Spoil pile must be at least 1.0m back from trench edge"),
});

export const PERMIT_TYPE_REGISTRY: Record<PermitType, PermitTypeDefinition> = {
  HOT_WORK: {
    type: "HOT_WORK",
    title: "Hot Work Permit",
    shortCode: "HW",
    color: "amber",
    iconName: "Flame",
    description: "Required for any work involving open flames, welding, grinding, torch cutting, or sparking tools.",
    highRiskCategory: true,
    zodSchema: HotWorkSchema,
    fields: [
      {
        name: "hotWorkType",
        label: "Type of Hot Work",
        type: "select",
        required: true,
        options: [
          { label: "Welding (Arc / TIG / MIG)", value: "welding" },
          { label: "Grinding", value: "grinding" },
          { label: "Cutting / Gas Torch", value: "cutting" },
          { label: "Soldering / Brazing", value: "soldering" },
        ],
        defaultValue: "welding",
      },
      {
        name: "fireWatchAssigned",
        label: "Fire Watch Assigned (Name / Badge)",
        type: "text",
        required: true,
        placeholder: "e.g. Ramesh K. (Badge #FW-104)",
        helpText: "Must remain on duty during work and for 30 minutes post-work.",
      },
      {
        name: "fireExtinguisherType",
        label: "Fire Extinguisher Type Present",
        type: "select",
        required: true,
        options: [
          { label: "DCP (Dry Chemical Powder - 6kg)", value: "DCP" },
          { label: "CO2 (Carbon Dioxide - 4.5kg)", value: "CO2" },
          { label: "Mechanical Foam (9L)", value: "Foam" },
          { label: "Pressurized Water", value: "Water" },
        ],
        defaultValue: "DCP",
      },
      {
        name: "combustiblesClearedRadius",
        label: "Combustibles Cleared Radius",
        type: "number",
        unit: "metres",
        required: true,
        defaultValue: 10,
        placeholder: "10",
        helpText: "Standard safety distance is 10 metres (or 35 feet) from hot work.",
      },
      {
        name: "gasTestLelPercent",
        label: "Gas Test - LEL (Lower Explosive Limit)",
        type: "number",
        unit: "%",
        required: true,
        placeholder: "0.0",
        defaultValue: 0,
        helpText: "Must be 0% (never exceed 5% in plant environments).",
      },
      {
        name: "gasTestO2Percent",
        label: "Gas Test - Oxygen (O2)",
        type: "number",
        unit: "%",
        required: true,
        placeholder: "20.9",
        defaultValue: 20.9,
        helpText: "Safe atmospheric range: 19.5% to 23.5%.",
      },
      {
        name: "gasTestTestedAt",
        label: "Gas Test Recorded At",
        type: "datetime-local",
        required: true,
        helpText: "Gas tests must be conducted within 2 hours prior to hot work.",
      },
      {
        name: "gasTesterName",
        label: "Authorized Gas Tester Name",
        type: "text",
        required: true,
        placeholder: "e.g. S. Murugan (Certified Gas Inspector)",
      },
    ],
    defaultHazards: [
      { id: "fire_explosion", label: "Fire & Explosion from Sparks / Slag", description: "Flammable vapors or oil residue nearby", severity: "CRITICAL" },
      { id: "toxic_fumes", label: "Toxic Welding Fumes & Gases", description: "Metal fumes, ozone, nitrogen oxides", severity: "HIGH" },
      { id: "radiation_burns", label: "UV/IR Radiation Arc Flash", description: "Skin and retinal eye burns", severity: "MEDIUM" },
      { id: "hot_slag_drops", label: "Falling Hot Slag / Droplets", description: "Sparks falling to lower levels or drains", severity: "HIGH" },
    ],
    defaultPPE: [
      { id: "welding_helmet", label: "Auto-Darkening Welding Helmet / Goggles", category: "EYES_FACE", isMandatory: true },
      { id: "leather_gloves", label: "Heavy Leather Welding Gloves", category: "HANDS", isMandatory: true },
      { id: "leather_apron", label: "Flame-Retardant Leather Apron / Spats", category: "BODY", isMandatory: true },
      { id: "safety_shoes", label: "Steel-Toe Heat-Resistant Safety Boots", category: "FEET", isMandatory: true },
      { id: "fume_respirator", label: "N95 / Fume Particulate Respirator", category: "RESPIRATORY" },
    ],
    precautions: [
      { id: "hw_p1", text: "Flammable liquids, gases, rags, and combustible materials cleared within 10m radius.", defaultChecked: true },
      { id: "hw_p2", text: "Sewers, floor drains, and pipe penetrations covered with wet fire blankets.", defaultChecked: true },
      { id: "hw_p3", text: "Charged fire extinguisher inspected, tagged, and stationed immediately at the job site.", defaultChecked: true },
      { id: "hw_p4", text: "Continuous gas monitoring or calibrated pre-job gas test verified 0% LEL.", defaultChecked: true },
      { id: "hw_p5", text: "Fire watch assigned with communication horn/radio and instructed on emergency shutdown.", defaultChecked: true },
    ],
  },

  CONFINED_SPACE: {
    type: "CONFINED_SPACE",
    title: "Confined Space Entry Permit",
    shortCode: "CS",
    color: "red",
    iconName: "ShieldAlert",
    description: "Required for entry into tanks, vessels, boilers, pits, siloes, manholes, or enclosed spaces with limited egress.",
    highRiskCategory: true,
    zodSchema: ConfinedSpaceSchema,
    fields: [
      {
        name: "spaceId",
        label: "Confined Space Identifier / Vessel #",
        type: "text",
        required: true,
        placeholder: "e.g. Storage Tank T-402, Column C-201 Bottom",
      },
      {
        name: "entryPoint",
        label: "Designated Entry Point / Manway",
        type: "text",
        required: true,
        placeholder: "e.g. Manway MW-01 (South side, Grade Level)",
      },
      {
        name: "atmosphericTestO2",
        label: "Atmospheric O2 Reading",
        type: "number",
        unit: "%",
        required: true,
        defaultValue: 20.9,
        helpText: "Safe range: 19.5% - 23.5%.",
      },
      {
        name: "atmosphericTestLel",
        label: "Atmospheric Combustible Gas (LEL)",
        type: "number",
        unit: "%",
        required: true,
        defaultValue: 0,
        helpText: "Must be 0% (action level < 5%).",
      },
      {
        name: "atmosphericTestH2sPpm",
        label: "Toxic Gas - H2S (Hydrogen Sulfide)",
        type: "number",
        unit: "ppm",
        required: true,
        defaultValue: 0,
        helpText: "OSHA ceiling: 10 ppm. Safe target: 0 ppm.",
      },
      {
        name: "atmosphericTestCoPpm",
        label: "Toxic Gas - CO (Carbon Monoxide)",
        type: "number",
        unit: "ppm",
        required: true,
        defaultValue: 0,
        helpText: "Safe ceiling: < 25 ppm.",
      },
      {
        name: "atmosphericTestTime",
        label: "Atmospheric Test Recorded At",
        type: "datetime-local",
        required: true,
      },
      {
        name: "atmosphericTesterName",
        label: "Certified Gas Tester Name",
        type: "text",
        required: true,
        placeholder: "e.g. V. Krishnan (Industrial Hygienist)",
      },
      {
        name: "standbyAttendantName",
        label: "Standby Attendant (Hole Watch)",
        type: "text",
        required: true,
        placeholder: "e.g. K. Balaji (Badge #HA-302)",
        helpText: "Must remain stationed at manway at all times; NEVER enters the space.",
      },
      {
        name: "rescuePlan",
        label: "Emergency Rescue Plan & Equipment",
        type: "textarea",
        required: true,
        placeholder: "Tripod with retrieval winch mounted, emergency SCBA present, plant rescue team on standby via Channel 4.",
      },
      {
        name: "ventilationMethod",
        label: "Forced Ventilation Method",
        type: "text",
        required: true,
        placeholder: "e.g. Continuous 2000 CFM explosion-proof blower",
      },
      {
        name: "entryExitLogSummary",
        label: "Initial Entrants Roster",
        type: "text",
        placeholder: "e.g. 2 entrants: P. Kumar, R. Sharma",
      },
    ],
    defaultHazards: [
      { id: "asphyxiation", label: "Oxygen Deficiency / Asphyxiation", description: "O2 level drops below 19.5%", severity: "CRITICAL" },
      { id: "toxic_atmosphere", label: "Toxic Gas Inhalation (H2S / CO / VOCs)", description: "Deadly gases trapped in sludge/scale", severity: "CRITICAL" },
      { id: "engulfment", label: "Engulfment / Entrapment", description: "Liquids, slurries, or bulk solids flow", severity: "CRITICAL" },
      { id: "heat_stress", label: "Heat Stress / Restricted Movement", description: "High temperature and humidity inside vessel", severity: "HIGH" },
    ],
    defaultPPE: [
      { id: "scba_escape", label: "Emergency Escape Breathing Apparatus (EEBA / SCBA)", category: "RESPIRATORY", isMandatory: true },
      { id: "full_harness", label: "Full Body Retrieval Harness (with D-ring)", category: "FALL_PROTECTION", isMandatory: true },
      { id: "4gas_monitor", label: "Personal Continuous 4-Gas Detector", category: "RESPIRATORY", isMandatory: true },
      { id: "chemical_suit", label: "Tychem / Chemical Protective Coverall", category: "BODY" },
      { id: "intrinsically_safe_light", label: "Intrinsically Safe (ATEX/Ex-rated) Headlamp", category: "HEAD", isMandatory: true },
    ],
    precautions: [
      { id: "cs_p1", text: "Physical mechanical isolation verified (spaded / blinded / disconnected piping).", defaultChecked: true },
      { id: "cs_p2", text: "Electrical and motor agitators locked and tagged out (LOTO).", defaultChecked: true },
      { id: "cs_p3", text: "Continuous positive forced air ventilation operating and confirmed flowing.", defaultChecked: true },
      { id: "cs_p4", text: "Atmosphere tested at top, middle, and bottom levels immediately prior to entry.", defaultChecked: true },
      { id: "cs_p5", text: "Retrieval tripod, winch, and harness tether tested and ready at entry.", defaultChecked: true },
      { id: "cs_p6", text: "Standby attendant briefed: will NOT enter space for any reason during an emergency.", defaultChecked: true },
    ],
  },

  WORKING_AT_HEIGHT: {
    type: "WORKING_AT_HEIGHT",
    title: "Working at Height Permit",
    shortCode: "WAH",
    color: "blue",
    iconName: "ArrowUpCircle",
    description: "Required for any work performed at an elevation of 1.8 metres (6 feet) or higher with potential fall hazard.",
    highRiskCategory: false,
    zodSchema: WorkingAtHeightSchema,
    fields: [
      {
        name: "heightInMetres",
        label: "Working Height Elevation",
        type: "number",
        unit: "metres",
        required: true,
        defaultValue: 3.5,
        placeholder: "e.g. 5.5",
      },
      {
        name: "accessMethod",
        label: "Access / Working Platform Method",
        type: "select",
        required: true,
        options: [
          { label: "Scaffolding (Green-Tagged)", value: "scaffold" },
          { label: "MEWP (Boom Lift / Scissor Lift)", value: "MEWP" },
          { label: "Secured Extension / Step Ladder", value: "ladder" },
          { label: "Rope Access System", value: "rope" },
        ],
        defaultValue: "scaffold",
      },
      {
        name: "fallArrestEquipment",
        label: "Fall Arrest & Restraint Equipment",
        type: "text",
        required: true,
        placeholder: "Full body harness with dual shock-absorbing lanyards and 100% tie-off",
      },
      {
        name: "anchorPointChecked",
        label: "Certified Anchor Point Verified (Rated >= 22kN / 5000 lbs)",
        type: "boolean",
        required: true,
        defaultValue: true,
      },
      {
        name: "barricadingBelow",
        label: "Ground Drop Zone Barricaded & Danger Taped",
        type: "boolean",
        required: true,
        defaultValue: true,
      },
    ],
    defaultHazards: [
      { id: "fall_from_height", label: "Fall from Elevation to Lower Level", description: "Fatal or severe fall injury", severity: "CRITICAL" },
      { id: "falling_objects", label: "Dropped Tools / Materials onto Personnel Below", description: "Head and body impact hazard", severity: "HIGH" },
      { id: "scaffold_collapse", label: "Structural Instability / Scaffold Failure", description: "Inadequate planking or missing bracing", severity: "CRITICAL" },
      { id: "high_winds", label: "Adverse Weather / Wind Gusts", description: "Loss of balance at elevation", severity: "MEDIUM" },
    ],
    defaultPPE: [
      { id: "fall_harness", label: "Full Body Harness with Shock Absorber & Double Lifeline", category: "FALL_PROTECTION", isMandatory: true },
      { id: "chin_strap_helmet", label: "Hard Hat with 4-Point Chin Strap", category: "HEAD", isMandatory: true },
      { id: "tool_tethers", label: "Tool Lanyards / Wrist Tethers (Prevent Dropped Tools)", category: "BODY", isMandatory: true },
      { id: "anti_slip_boots", label: "Non-Slip High-Grip Safety Boots", category: "FEET", isMandatory: true },
    ],
    precautions: [
      { id: "wah_p1", text: "Scaffold inspected by competent person and displaying current GREEN inspection tag.", defaultChecked: true },
      { id: "wah_p2", text: "All workers trained and certified in full-body harness donning and 100% tie-off rules.", defaultChecked: true },
      { id: "wah_p3", text: "Anchor point selected is structural beam or approved lifeline rated at 5,000 lbs.", defaultChecked: true },
      { id: "wah_p4", text: "Toe boards and edge toe-rails installed on working platform.", defaultChecked: true },
      { id: "wah_p5", text: "Red danger tape barricading perimeter below with 'Overhead Work' signs.", defaultChecked: true },
    ],
  },

  ELECTRICAL_LOTO: {
    type: "ELECTRICAL_LOTO",
    title: "Electrical Isolation & LOTO Permit",
    shortCode: "LOTO",
    color: "purple",
    iconName: "Zap",
    description: "Required for servicing equipment with electrical, pneumatic, hydraulic, or stored mechanical energy.",
    highRiskCategory: true,
    zodSchema: ElectricalLotoSchema,
    fields: [
      {
        name: "equipmentTag",
        label: "Target Equipment Tag / Motor Number",
        type: "text",
        required: true,
        placeholder: "e.g. MCC-04-PUMP-02 (Cooling Water Pump Motor)",
      },
      {
        name: "voltageLevel",
        label: "Operating Voltage Level",
        type: "text",
        required: true,
        placeholder: "e.g. 415V 3-Phase AC, 3.3kV, 11kV, 24V DC",
      },
      {
        name: "isolationPointsList",
        label: "List of Physical Isolation Points & Breakers",
        type: "textarea",
        required: true,
        placeholder: "1. Feeder Breaker CB-14 racked out at Substation #2\n2. Control fuse pulled\n3. Suction valve closed and chained",
      },
      {
        name: "lockNumbers",
        label: "Safety Padlock Numbers Applied",
        type: "text",
        required: true,
        placeholder: "e.g. LOTO-LOCK-881, LOTO-LOCK-882",
      },
      {
        name: "tagNumbers",
        label: "Danger Tag Serial Numbers",
        type: "text",
        required: true,
        placeholder: "e.g. DANGER-TAG-4091, DANGER-TAG-4092",
      },
      {
        name: "earthingApplied",
        label: "Temporary Earth Grounds Applied (where required)",
        type: "boolean",
        required: true,
        defaultValue: true,
      },
      {
        name: "testedDeadByWhom",
        label: "Zero Energy Verified / Tested Dead By",
        type: "text",
        required: true,
        placeholder: "e.g. M. Natarajan (Licensed Senior Electrical Tech)",
        helpText: "Zero-voltage must be tested using calibrated multimeters/voltage detector probe.",
      },
    ],
    defaultHazards: [
      { id: "electrocution", label: "Electrocution / Electric Shock", description: "Contact with energized electrical conductors", severity: "CRITICAL" },
      { id: "arc_flash", label: "Arc Flash / Arc Blast", description: "Catastrophic short-circuit fireball and explosive pressure", severity: "CRITICAL" },
      { id: "unexpected_start", label: "Unexpected Machine Start-up / Stored Energy", description: "Hydraulic, pneumatic, or gravitational energy release", severity: "HIGH" },
    ],
    defaultPPE: [
      { id: "arc_flash_suit", label: "Arc-Rated Face Shield & Balaclava (8-40 cal/cm²)", category: "EYES_FACE", isMandatory: true },
      { id: "dielectric_gloves", label: "Class 0 / Class 2 Dielectric Insulated Gloves with Leather Protectors", category: "HANDS", isMandatory: true },
      { id: "esd_boots", label: "Dielectric Safety Footwear (EH Rated)", category: "FEET", isMandatory: true },
      { id: "arc_clothing", label: "NFPA 70E Arc-Resistant Cotton Coverall", category: "BODY", isMandatory: true },
    ],
    precautions: [
      { id: "loto_p1", text: "Primary breaker opened, racked out, and visual air-gap confirmed.", defaultChecked: true },
      { id: "loto_p2", text: "Personal safety padlock applied to lockout hasp with non-reusable Danger Tag.", defaultChecked: true },
      { id: "loto_p3", text: "Zero energy verified: live-dead-live multi-meter test conducted on all phases.", defaultChecked: true },
      { id: "loto_p4", text: "Stored energy dissipated (capacitors discharged, hydraulic pressure bled).", defaultChecked: true },
      { id: "loto_p5", text: "Attempted machine restart test performed from local push-button to prove dead.", defaultChecked: true },
    ],
  },

  EXCAVATION: {
    type: "EXCAVATION",
    title: "Excavation & Trenching Permit",
    shortCode: "EXC",
    color: "amber",
    iconName: "Tractor",
    description: "Required for mechanized or manual ground excavation deeper than 0.5 metres.",
    highRiskCategory: true,
    zodSchema: ExcavationSchema,
    fields: [
      {
        name: "excavationDepthMeters",
        label: "Estimated Excavation Depth",
        type: "number",
        unit: "metres",
        required: true,
        defaultValue: 1.5,
        placeholder: "e.g. 2.0",
      },
      {
        name: "soilType",
        label: "Soil Classification",
        type: "select",
        required: true,
        options: [
          { label: "Type A (Clay / Cohesive / Hard)", value: "Type A (Clay/Hard)" },
          { label: "Type B (Silt / Sandy Loam / Medium)", value: "Type B (Silt/Sandy Loam)" },
          { label: "Type C (Gravel / Loose Sand / Submerged)", value: "Type C (Gravel/Loose Sand)" },
        ],
        defaultValue: "Type B (Silt/Sandy Loam)",
      },
      {
        name: "undergroundUtilityClearance",
        label: "Underground Utilities & Cables Scanned / Cleared",
        type: "boolean",
        required: true,
        defaultValue: true,
      },
      {
        name: "shoringOrBenchMethod",
        label: "Cave-in Protection Method",
        type: "select",
        required: true,
        options: [
          { label: "Engineered Aluminum Trench Box / Shield", value: "Trench Box" },
          { label: "Hydraulic Aluminum Shoring", value: "Hydraulic Shoring" },
          { label: "45-Degree Benching / Stepped Sloping", value: "45-degree Benching" },
          { label: "34-Degree Continuous Sloping", value: "Continuous Sloping" },
        ],
        defaultValue: "Trench Box",
      },
      {
        name: "safeLadderDistanceMeters",
        label: "Egress Ladder Spacing",
        type: "number",
        unit: "metres",
        required: true,
        defaultValue: 7.5,
        helpText: "OSHA maximum lateral travel to ladder is 7.5m (25 ft).",
      },
      {
        name: "spoilPileDistanceMeters",
        label: "Excavated Spoil Pile Setback Distance",
        type: "number",
        unit: "metres",
        required: true,
        defaultValue: 1.0,
        helpText: "Must be at least 1.0m (3 ft) from edge to prevent roll-in.",
      },
    ],
    defaultHazards: [
      { id: "cave_in", label: "Trench Cave-in / Soil Collapse", description: "Suffocation and crushing under shifting soil", severity: "CRITICAL" },
      { id: "underground_utilities", label: "Striking Underground Gas / Electrical Lines", description: "Explosion, fire, or electrocution", severity: "CRITICAL" },
      { id: "hazardous_atmosphere", label: "Heavy Gas Accumulation in Trench", description: "Heavier-than-air gases (propane, H2S) pooling in pit", severity: "HIGH" },
    ],
    defaultPPE: [
      { id: "exc_hard_hat", label: "High-Visibility Hard Hat", category: "HEAD", isMandatory: true },
      { id: "hi_vis_vest", label: "Reflective Class 3 High-Visibility Safety Vest", category: "BODY", isMandatory: true },
      { id: "steel_toe", label: "Steel-Toe Heavy Duty Puncture-Resistant Boots", category: "FEET", isMandatory: true },
    ],
    precautions: [
      { id: "exc_p1", text: "As-built drawings reviewed and pipe/cable locator scan completed.", defaultChecked: true },
      { id: "exc_p2", text: "Trench box or shoring installed before personnel enter any trench > 1.2m.", defaultChecked: true },
      { id: "exc_p3", text: "Egress ladders extend at least 1m above trench surface.", defaultChecked: true },
      { id: "exc_p4", text: "Atmosphere tested prior to entry if excavation is near chemical/gas lines.", defaultChecked: true },
    ],
  },
};

export function getPermitTypeDefinition(type: PermitType): PermitTypeDefinition {
  const def = PERMIT_TYPE_REGISTRY[type];
  if (!def) {
    throw new Error(`Unknown permit type: ${type}`);
  }
  return def;
}
